version: '3.7'
services:
  model_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '63332:5432'
    volumes:
      - ./docker_db:/var/lib/postgresql/data
  model_api:
    build: .
    ports:
      - 63274:63274
    volumes:
      - ./src/:/app/
    entrypoint: "npm run local"
    environment:
      DB_PORT: '63332'
      DB_HOST: model_db
      DB_PW: postgres
      DB_USER: postgres
      DB_NAME: whims_model_db